// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using Microsoft.ML;
using TechRSSReaderML.Model;

namespace TechRSSReaderML.Model
{
    public class ConsumeModel
    {
        private static Lazy<PredictionEngine<StarRatingInput, StarRatingOutput>> PredictionEngine = new Lazy<PredictionEngine<StarRatingInput, StarRatingOutput>>(CreatePredictionEngine);

        public static string MLNetModelPath = Path.GetFullPath("MLModel.zip");

        // For more info on consuming ML.NET models, visit https://aka.ms/mlnet-consume
        // Method for consuming model in your app
        public static StarRatingOutput Predict(StarRatingInput input)
        {
            StarRatingOutput result = PredictionEngine.Value.Predict(input);
            return result;
        }

        public static PredictionEngine<StarRatingInput, StarRatingOutput> CreatePredictionEngine()
        {
            // Create new MLContext
            MLContext mlContext = new MLContext();

            // Load model & create prediction engine
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<StarRatingInput, StarRatingOutput>(mlModel);

            return predEngine;
        }
    }
}
