// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.ML;
using TechRSSReaderML.Model;

namespace TechRSSReaderML.Model
{
    public class ConsumeModel
    {
        private static Lazy<PredictionEngine<UserInterestInput, UserInterestOutput>> PredictionEngine = new Lazy<PredictionEngine<UserInterestInput, UserInterestOutput>>(CreatePredictionEngine);

        // For more info on consuming ML.NET models, visit https://aka.ms/mlnet-consume
        // Method for consuming model in your app
        public static UserInterestOutput Predict(UserInterestInput input)
        {
            UserInterestOutput result = PredictionEngine.Value.Predict(input);
            return result;
        }

        public static PredictionEngine<UserInterestInput, UserInterestOutput> CreatePredictionEngine()
        {
            // Create new MLContext
            MLContext mlContext = new MLContext();

            // Load model & create prediction engine
            string modelPath = @"C:\Users\awoodyatt\AppData\Local\Temp\MLVSTools\TechRSSReaderML\TechRSSReaderML.Model\MLModel.zip";
            ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<UserInterestInput, UserInterestOutput>(mlModel);

            return predEngine;
        }
    }
}   
