// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace TechRSSReaderML.Model
{
    public class StarRatingOutput
    {
        public float Score { get; set; }
    }
}
