// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace TechRSSReaderML.Model
{
    public class StarRatingInput
    {
        [ColumnName("Id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("CreatedBy"), LoadColumn(1)]
        public string CreatedBy { get; set; }


        [ColumnName("Created"), LoadColumn(2)]
        public string Created { get; set; }


        [ColumnName("LastModifiedBy"), LoadColumn(3)]
        public string LastModifiedBy { get; set; }


        [ColumnName("LastModified"), LoadColumn(4)]
        public string LastModified { get; set; }


        [ColumnName("Author"), LoadColumn(5)]
        public string Author { get; set; }


        [ColumnName("BlogId"), LoadColumn(6)]
        public float BlogId { get; set; }


        [ColumnName("Categories"), LoadColumn(7)]
        public string Categories { get; set; }


        [ColumnName("Content"), LoadColumn(8)]
        public string Content { get; set; }


        [ColumnName("Description"), LoadColumn(9)]
        public string Description { get; set; }


        [ColumnName("Link"), LoadColumn(10)]
        public string Link { get; set; }


        [ColumnName("PublishingDate"), LoadColumn(11)]
        public string PublishingDate { get; set; }


        [ColumnName("PublishingDateString"), LoadColumn(12)]
        public string PublishingDateString { get; set; }


        [ColumnName("RetrievedDateTime"), LoadColumn(13)]
        public string RetrievedDateTime { get; set; }


        [ColumnName("RssId"), LoadColumn(14)]
        public string RssId { get; set; }


        [ColumnName("Title"), LoadColumn(15)]
        public string Title { get; set; }


        [ColumnName("UserInterested"), LoadColumn(16)]
        public string UserInterested { get; set; }


        [ColumnName("UserInterestPrediction"), LoadColumn(17)]
        public float UserInterestPrediction { get; set; }


        [ColumnName("ReadAlready"), LoadColumn(18)]
        public bool ReadAlready { get; set; }


        [ColumnName("UserRating"), LoadColumn(19)]
        public float UserRating { get; set; }


        [ColumnName("UserRatingPrediction"), LoadColumn(20)]
        public float UserRatingPrediction { get; set; }


    }
}
